### ISSUE TITLE
Duplicates Glitch again?

### ISSUE THREAD

**Issue by pironic** [WritheM/IntelliMerge#10]
**Describe the bug**
"I’ve noticed new songs added to the playlists I’m merging have been coming in twice since the update. Is that a known issue?"

**Comment by pironic** [comment]
Unable to reproduce. Waiting on more information.

**Comment by pironic** [comment]
bah... it did it again this morning: 
![image](https://user-images.githubusercontent.com/541154/81857547-a7cd5d00-951f-11ea-8aba-49a0c7634ab2.png)

**Comment by pironic** [comment]
concurrency issue? 2 seconds apart. will investigate further.
![image](https://user-images.githubusercontent.com/541154/81858087-69846d80-9520-11ea-8eb2-736adef88ba2.png)

**Comment by pironic** [comment]
fixed in next minor build

**Comment by SKArcade** [comment]
Thanks for fixing this  :)
