### ISSUE TITLE
Empty Playlist(s)

### ISSUE THREAD

**Issue by Zheta** [WritheM/IntelliMerge#30]
**Describe the bug**
Playlist is completely empty.

**To Reproduce**
Opened Spotify and long-time merged playlist was suddenly completely empty. Did try completely remaking playlist and still empty.

**Expected behavior**
Playlist to be full of songs where I left it.

**Screenshots**
Remade playlist: (before remake still had album art)
![remade](https://user-images.githubusercontent.com/7018644/158925838-d9a6e602-0bd1-4a58-8fa5-377de0438334.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser: Firefox - 98.0.1 (64-bit)
 - Build [e.g. 3500] (This is found on the about/faq page in the change log section.

**Smartphone (please complete the following information):**
 - Build: v2.2.1.4505

**Additional context**
Y'all may already be aware of this happening, but I didn't know what to do other than submit a bug report. Not sure if there is another way to contact. Thanks!

**Comment by Zheta** [comment]
My second MPL, that's more of a test case and less used, does seem to be working still/again? Maybe only the "Zoe + 80s / Modern / Retro Synth" that isn't working.

**Comment by Zheta** [comment]
![Screenshot 2022-03-17 213413](https://user-images.githubusercontent.com/7018644/158926662-87a0d44e-9166-4585-8216-17db0d23dc62.png)

This is the one that seems to be working.

**Comment by Zheta** [comment]
...Other playlist seems to be working again after the remake and a few refreshes... ^^
![grr](https://user-images.githubusercontent.com/7018644/158928637-36213227-fb3c-4a87-9470-ab1cf7452a65.png)
;

**Comment by pironic** [comment]
Hey Zheta, this is certainly a way we can help but if it's an isolated issue we can help via an email to admin@writhem.com (along with your support key from your profile page). I'll keep this issue open until we can identify that it's just an isolated issue or that it has been resolved. If it affects more than just this one playlist, then we'll close the bug report. 

Thank you for reaching out and supporting us :-)

**Comment by pironic** [comment]
Hey Zheta, this appears to be a stale issue. Please respond if you are still having issues and require additional help. Thanks very much for using Intellimerge for Spotify.
