### ISSUE TITLE
Suppress Playlist Description #log updates

### ISSUE THREAD

**Issue by spykah** [WritheM/IntelliMerge#33]
**Is your feature request related to a problem? Please describe.**
When updating my master playlist the description is updated with update information (see added screenshot). I don't want the description of my master playlist to be altered. Can I turn this feature off?

**Describe the solution you'd like**
If possible, a button to turn of playlist description altering.

**Describe alternatives you've considered**
none

**Additional context**
![playlist](https://user-images.githubusercontent.com/80481473/215750784-dfa0c161-3adc-4294-82f4-2726e18d40ef.png)

**Comment by pironic** [comment]
Great idea. I'll put this on the fast-track for development. That being said... i'm a bit behind right now... working on another full-time project that is taking up my time. Let's put this near the top though. 

could easily put another toggle here: 
![image](https://user-images.githubusercontent.com/541154/215914970-c6261759-f7ea-4578-9966-9e2501234eee.png)

**Comment by spykah** [comment]
Thanks! Ofcourse, good luck with the other project! :)

**Comment by pironic** [comment]
Added in next release. 2.3.1
