### ISSUE TITLE
Lost link to Master Playlists in Spotify

### ISSUE THREAD

**Issue by Rouzax** [WritheM/IntelliMerge#35]
I have a few Master playlists that still exist in Spotify but IntelliMerge has lost connection to.
![image](https://github.com/WritheM/IntelliMerge/assets/4103090/94c9314e-21af-49bc-be2b-a203a6c14abb)
![image](https://github.com/WritheM/IntelliMerge/assets/4103090/e0ea3de8-39b6-4a2a-8176-12c2952c1371)
![image](https://github.com/WritheM/IntelliMerge/assets/4103090/0a93c3b0-73ca-4a64-a0c3-1bee5b13b939)

**Comment by Rouzax** [comment]
After editing the Playlist in the IntelliMerge Editor it creates a new playlist in Spotify
![image](https://github.com/WritheM/IntelliMerge/assets/4103090/8b714b8a-9333-4c95-b783-d51c7cf7f929)

**Comment by Rouzax** [comment]
Is there a way to relink it to the previous one as that has history and shared with others?

**Comment by pironic** [comment]
Hey Rouzax, that's a bummer that it disconnected :( September is well beyond the extent of my detailed logs though, so I can't even look back at that to see why it would have disconnected. 

Two options going forward though: 
 
1. Keep the Spotify playlist but make a new playlist profile on Intellimerge (and have to make your connections again).
2. Keep the Intellimerge profile (and connections/history) but make a new Spotify playlist.

It sounds like option 1 is the desired option. To do that you'll have to make the connections again but tell intellimerge about your existing spotify playlist. This will allow intellimerge to change an existing spotify playlist. Head to the https://writhem.net/intellimerge/editor.php Playlist Editor and click the ![image](https://github.com/WritheM/IntelliMerge/assets/541154/7e5773bc-db53-43fd-8e0b-c0d1726998d3) button to Import an existing playlist. Paste in the spotify playlist uri which you can obtain from your spotify client by click on the share button and selecting Spotify URI. (I've noticed on windows that the only two options by default are Copy link to playlist and Embed playlist, but if you hold the ctrl button it changes the first one to 'Copy Spotify URI'. That's the one you want. ) 

Once intellimerge has imported the existing list you might want to turn it off immediately until you finish making the connections. Once you think it looks good, turn it back on. It'll pick up from where it left off. 

I'm going to close this comment, but let me know if we should re-open or you need any further help with it.

**Comment by Rouzax** [comment]
Thanks, I understand it is a while ago. Didn't really notice it untill now :)
I've opted for a new created playlist and link the old MPL to the new one to import the history and delete the old one after the first sync.
